---

- name: Loop Until example
  shell: echo -n Z >> myfile && cat myfile
  register: output #var for write result of loop
  delay: 2 # in seconds
  retries: 10 # default = 3
  until: output.stdout.find("ZZZZ") == false

- name: Print Final Output
  debug:
    var: output.stdout

